package com.dreamdisplays.api.media.stream.model

import com.dreamdisplays.api.Unstable

/**
 * One selectable subtitle / caption track exposed by a resolver, e.g. a YouTube caption track.
 *
 * @since 1.10.x
 */
@Unstable
data class SubtitleTrack(
    /** Direct URL to the subtitle file (WebVTT). */
    val url: String,

    /** Language code (e.g. "en", "ru"), used as the stable identity across re-resolves. */
    val lang: String,

    /** Human-readable language / track name, if the provider exposed one. */
    val displayName: String?,

    /** True for auto-generated (ASR) captions, as opposed to uploader-provided ones. */
    val isAutoGenerated: Boolean = false,
)
